changelog:
  categories:
    - title: Breaking
      labels: [breaking]
    - title: Features
      labels: [enhancement, feat]
    - title: Fixes
      labels: [bug, fix]
    - title: Docs
      labels: [docs]
    - title: Performance
      labels: [perf]
    - title: Dependencies
      labels: [deps]
    - title: Other
      labels: ["*"]
  exclude:
    labels: [ignore-release]
